### ISSUE TITLE
cpr dependency not building on Windows MSVS 2015

### ISSUE THREAD

**Issue by ShamanTcler** [thclark/cpplot#18]
conan install . --install-folder C:/Users/xxxx/github/cpplot/build/release
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=14
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

ERROR: cpr/1.5.0: Error in configure() method, line 39
        if self.options["libcurl"].with_openssl == False:  # 'is False' doesn't work here (see conan-io/conan#3620)
        ConanException: option 'with_openssl' doesn't exist
Possible options are []

I was using the conan-center as my remote.

**Comment by thclark** [comment]
OK. So, the cpr library isn't presently used. It's there in the build system from when I was messing with plotly online (it's used in [online.h](https://github.com/thclark/cpplot/blob/458d26f99aa4298e7260bb5da65ba7915f098f5f/source/online.h#L160) to post figures to plotly online.

I'd like to come back to whether an online feature should be kept - so cross-referencing #10 as some discussion should be made.

However, in the meantime at least, I'm quite happy with removing the cpr dependency because I don't think it's actually linked anywhere.

Give me half an hour.

**Comment by thclark** [comment]
OK. 36 minutes. Give that a try @ShamanTcler

**Comment by ShamanTcler** [comment]
Update I switched to using conan-cmake (https://github.com/conan-io/cmake-conan) in the CMakelists.txt file and then gave it:

conan_cmake_run(
                REQUIRES
                    eigen/3.3.7
                    nlohmann_json/3.8.0
                    boost/1.73.0
                    glog/0.4.0
                    gtest/1.10.0
                    tbb/2020.1
                IMPORTS
                    ${CONANIMPORTS}
                BASIC_SETUP
                	CMAKE_TARGETS
                )

And it compiled but did not link. 

The switch to using conan-cmake was because it gets rid of the install issue... though you do need to have a conan.cmake file...

**Comment by thclark** [comment]
Have you still got the same problem of not linking against cpr? or is it a new problem?
