### ISSUE TITLE
Can u please add examples like "reading csv" & plotting using cpplot lib

### ISSUE THREAD

**Issue by abhi3700** [thclark/cpplot#4]
TODO:
1. reading csv lib --> [DataFrame](https://github.com/hosseinmoein/DataFrame)
2. plotting using your lib.

Actually, its' getting very difficult to import & starting project. Basically, if you can add **"Getting Started"** section.

NOTE: There was a mention in the README of C++ API. What's the status of the project?

**Comment by abhi3700** [comment]
This is my opinion in terms of simplicity of using your lib.

In Python, we simply install the package & get started very conveniently. But I tried doing this here using your lib.
But I started getting errors like this:
```
In file included from plot.cpp:1:0:
../src/cpplot.h:30:10: fatal error: Eigen/Dense: No such file or directory
 #include <Eigen/Dense>
          ^~~~~~~~~~~~~
compilation terminated.
```
And this is not a great thing.

**Comment by thclark** [comment]
## OSS/GitHub Issues Etiquette

Generally it helps OSS project maintainers if an issue relates to one thing, with a well crafted question. [StackOverflow](https://stackoverflow.com/help/how-to-ask) has a good guide on how to ask questions, I suggest taking a look, it'll help you get better answers online.

Also, starting an issue with a TODO list for the maintainers is likely to get people annoyed with you pretty quickly. Remember you're asking strangers to do work for free for you. **At least be polite about it, instead of bluntly listing things you want then ranting about the current state of the project**, especially when you're learning a new language and clearly haven't figured out it all out yet.

## Answers

### Build systems

Unfortunately C++ build systems aren't nearly as simple as python, but that's not my fault! 

In your case, Eigen is missing, which is already listed [here in the readme](https://github.com/thclark/cpplot#third-party-dependencies) as a third party dependency. If you're not familiar with building in c++, I'd suggest doing a few tutorials with CMake, which is a very useful build system.

You may also want to check out conan and vcpkg - cpplot isn't on those package mangers yet as it's not sufficiently mature, but they may help you with other things.

You can check one of my other libraries, [es-flow](https://github.com/octue/es-flow) for an example of how to actually use eigen and cpplot in a project, although I should say I'm [currently upgrading es-flow's build systems](https://github.com/octue/es-flow/releases/tag/0.1.2-alpha.2) and work is ongoing, but they're already a pretty good example.

However, feedback is noted - I'll add a Getting Started in due course, but fair warning, it'll assume basics of knowledge working with C++. [I have created an issue to track this](https://github.com/thclark/cpplot/issues/5) and I also need to do a wide range of stuff to spin this up toward a sensible project, now it's getting a bit of traction - my plan is to add proper project roadmap, documentation etc etc like i have with `es-flow`.

### Examples

Also covered in the above new issue. In the meantime, I'd strongly recommend looking at the test code - each test is basically an example for how to make a different kind of plot.

### C++ API

It's already in C++ and therefore its API is in C++. No idea what you're talking about here!

### Project Status

Current status of the library is that it's maintained, although like most OSS maintainers I have limited time and it's a project of passion!

### CSV Reader

On your request for a CSV reader, that would be way way way out of the scope of this project. There are plenty of examples (from a quick google search) of how to do this.

Although if you submit some example code (and a csv file) to read a CSV into an Eigen matrix then plot it with cpplot, I'd happily turn that into an example in the docs for others to use.

### Dataframes

Dataframes look really interesting, again I'd welcome a standalone example demonstrating how to plot from them. There's no need for a specific integration though - it's straightforward to initialise an Eigen array from a std::vector<double> so you can get data (sliced, reduced, windowed, whatever) out of a dataframe, point an Eigen array to it then plot using cpplot.
